CREATE TABLE IF NOT EXISTS PHRASES(
    ID INTEGER PRIMARY KEY,
    LANG TEXT NOT NULL,
    PHRASE TEXT NOT NULL,
    TRANSLATION TEXT NOT NULL,
    STATUS TEXT DEFAULT 'ACTIVE',
    CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFICATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);
